# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
dist: trusty # xenial
latex: false
fortran: false
r_check_args: "--no-manual --as--cran"
cache: packages
os:
  - linux
  - osx
r:
  - 3.4
  - release
  - devel
matrix:
  exclude:
  - r: 3.4
    os: osx
  - r: devel
    os: osx
env:
  global:
  - ENCRYPTION_LABEL: "3dc1811797c0"
notifications:
  email:
    on_success: change
    on_failure: change
r_packages:
  - covr
  - pkgdown
after_success:
  - test "$TRAVIS_R_VERSION_STRING" = "release" -a "$TRAVIS_OS_NAME" == "linux" && .travis/deploy.sh || true
